name: StockMarketPlugin
version: '${version}'
main: com.github.woxox.stockmarketplugin.StockMarketPlugin
api-version: '1.20'
description: "A Stock Market Plugin"

commands:
  test:
    description: 테스트 명령어
    usage: /test
  test2:
    description: 테스트 명령어 22
    usage: /test2
  stock:
    description: 주식 리스트
    usage: /stock
